import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import React from "react";
import {Toaster} from "react-hot-toast";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const roboto = Roboto({
    display: "swap",
    weight: ["400"],
    style: "normal",
    subsets: ["latin"],
});

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <script src={"https://kit.fontawesome.com/248f39001f.js"} crossOrigin="anonymous"></script>
            <title>AryanKumarOfficial</title>
        </head>
        <body className={`${roboto.className}`}>
        <Navbar/>
        <Toaster
            position="top-right"
            reverseOrder={false}
            toastOptions={{
                className: "",
                style: {
                    background: "#111827",
                    color: "#2dd4bf",
                    zIndex: 1,
                },
                duration: 5000,
            }}/>
        {children}
        {/*<Footer/>*/}
        </body>
        </html>
    );
}
