import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import React from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <script src={"https://kit.fontawesome.com/248f39001f.js"} crossOrigin="anonymous"></script>
            <title>AryanKumarOfficial</title>
        </head>
        <body className={` ${inter.className}`}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
